// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SWIMRMultiRef
SEXP SWIMRMultiRef(SEXP YinputIn, SEXP SListIn, SEXP KIn, SEXP phi1In, SEXP phi2In, SEXP max_iterIn, SEXP epsilonIn, SEXP initPList, SEXP initsMatList, SEXP initSigma_e2, SEXP initLambdaList, SEXP initZ);
RcppExport SEXP _SWIMR_SWIMRMultiRef(SEXP YinputInSEXP, SEXP SListInSEXP, SEXP KInSEXP, SEXP phi1InSEXP, SEXP phi2InSEXP, SEXP max_iterInSEXP, SEXP epsilonInSEXP, SEXP initPListSEXP, SEXP initsMatListSEXP, SEXP initSigma_e2SEXP, SEXP initLambdaListSEXP, SEXP initZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type YinputIn(YinputInSEXP);
    Rcpp::traits::input_parameter< SEXP >::type SListIn(SListInSEXP);
    Rcpp::traits::input_parameter< SEXP >::type KIn(KInSEXP);
    Rcpp::traits::input_parameter< SEXP >::type phi1In(phi1InSEXP);
    Rcpp::traits::input_parameter< SEXP >::type phi2In(phi2InSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max_iterIn(max_iterInSEXP);
    Rcpp::traits::input_parameter< SEXP >::type epsilonIn(epsilonInSEXP);
    Rcpp::traits::input_parameter< SEXP >::type initPList(initPListSEXP);
    Rcpp::traits::input_parameter< SEXP >::type initsMatList(initsMatListSEXP);
    Rcpp::traits::input_parameter< SEXP >::type initSigma_e2(initSigma_e2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type initLambdaList(initLambdaListSEXP);
    Rcpp::traits::input_parameter< SEXP >::type initZ(initZSEXP);
    rcpp_result_gen = Rcpp::wrap(SWIMRMultiRef(YinputIn, SListIn, KIn, phi1In, phi2In, max_iterIn, epsilonIn, initPList, initsMatList, initSigma_e2, initLambdaList, initZ));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SWIMR_SWIMRMultiRef", (DL_FUNC) &_SWIMR_SWIMRMultiRef, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_SWIMR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
