# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SWIMRMultiRef <- function(YinputIn, SListIn, KIn, phi1In, phi2In, max_iterIn, epsilonIn, initPList, initsMatList, initSigma_e2, initLambdaList, initZ) {
    .Call(`_SWIMR_SWIMRMultiRef`, YinputIn, SListIn, KIn, phi1In, phi2In, max_iterIn, epsilonIn, initPList, initsMatList, initSigma_e2, initLambdaList, initZ)
}

